/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-dim": "#d9d9e3",
                "surface-container": "#ededf7",
                "secondary": "#196b52",
                "tertiary-fixed": "#cde5ff",
                "tertiary-container": "#00659b",
                "on-error": "#ffffff",
                "secondary-fixed-dim": "#8ad6b8",
                "inverse-primary": "#b3c5ff",
                "error-container": "#ffdad6",
                "primary-fixed": "#dbe1ff",
                "on-tertiary": "#ffffff",
                "surface-variant": "#e2e2eb",
                "on-secondary-fixed": "#002117",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#003fa5",
                "primary-fixed-dim": "#b3c5ff",
                "on-background": "#1a1b22",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#1a1b22",
                "on-primary-fixed": "#00184a",
                "primary": "#0040a8",
                "on-secondary-fixed-variant": "#00513d",
                "secondary-container": "#a5f2d3",
                "background": "#faf8ff",
                "on-tertiary-fixed-variant": "#004b74",
                "error": "#ba1a1a",
                "tertiary": "#004c76",
                "on-tertiary-container": "#bedeff",
                "outline-variant": "#c3c6d5",
                "surface-container-low": "#f3f3fc",
                "on-primary-container": "#d0daff",
                "inverse-surface": "#2e3037",
                "on-tertiary-fixed": "#001d32",
                "primary-container": "#2b59c3",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#94ccff",
                "surface-container-high": "#e8e7f1",
                "on-secondary-container": "#217158",
                "surface": "#faf8ff",
                "on-primary": "#ffffff",
                "surface-container-highest": "#e2e2eb",
                "surface-bright": "#faf8ff",
                "on-surface-variant": "#434653",
                "secondary-fixed": "#a5f2d3",
                "surface-tint": "#2958c2",
                "inverse-on-surface": "#f0f0f9",
                "outline": "#747684"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
    plugins: [],
}